// import { Inter } from "next/font/google";
// import "./globals.css";
// import 'bootstrap/dist/css/bootstrap.min.css';

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "American Distributors LLC",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={inter.className} style={{margin: '0px !important'}}>{children}</body>
//     </html>
//   );
// }
"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import { Provider } from 'react-redux';
import store from "../redux/store"
import { usePathname } from 'next/navigation'
import { useEffect, useState } from "react";
import Swal from "sweetalert2";
import { useRouter } from 'next/navigation'
import Cookies from "js-cookie";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  const roleCookie = Cookies.get("role");
  const role = roleCookie ? JSON.parse(roleCookie) : null;


  const pathname = usePathname()
  const router = useRouter()
  const [showAlert, setShowAlert] = useState(false);
  useEffect(() => {
    if (pathname?.toLocaleLowerCase() === "/admin" && !role?.administrator ) {
      router.push('/'); 
      setShowAlert(true);
    }
  }, [pathname, router]);

  
  
  useEffect(() => {
    if (showAlert) {
      Swal.fire({
        title: `You are not authorized. Please login as admin!`,
        icon: "warning",
        confirmButtonText: "LOGIN",
      }).then((res) => {
        if (res?.isConfirmed) {
          router.push(`/myaccount?tab=login`)
        }
      });
      setShowAlert(false);
    }
  }, [showAlert]);


  return (
    <html lang="en">
      <Provider store={store}>

        <body className={inter.className} style={{ margin: '0px !important' }}>
          {children}
        </body>
        {/* <script src="//code.tidio.co/hheqf7brygg0x3igya6tgz2pni8q5ceh.js" async></script> */}
      </Provider>
    </html>
  );
}
